sudo: true
language: python
python:
  - 2.7


install:

  - pip install python-coveralls
  - pip install coveralls
  - pip install coverage
  - pip install nose


  - pip install -r requirements.txt

before_script:
  - mysql -e "CREATE DATABASE catalog_tests_db;" 
  - mysql -e "CREATE USER 'cata'@'localhost' IDENTIFIED BY 'cata1';"
  - mysql -e "GRANT ALL PRIVILEGES ON catalog_tests_db .* TO 'cata'@'localhost;"

script: nosetests --with-coverage

after_success:
- coveralls
