sudo: true
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
services:
  - mysql
  
before_script:
  - mysql -u root -e "CREATE DATABASE test_catalog;"
  - mysql -u root -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON test_catalog .* TO 'test'@'localhost';"
  
after_success:
  coveralls
script:
- nosetests  --with-coverage 
