sudo: true
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
services:
  - postgresql
env:
  global:
    - export SECRET="TesT_catalog"
    - export APP_SETTINGS="development"
    - export DATABASE_URL="postgresql://postgres:postgres@localhost/test_db"
before_script:
  - psql -c "CREATE DATABASE test_db;" -U postgres
after_success:
  coveralls
script:
- nosetests  --with-coverage --cover-package=myapp
