sudo: true
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
services:
  - postgresql
env:
  global:
    - export FLASK_CONFIG="development"
    - export FLASK_APP = "run.py"
  
before_script:
  - psql -c "CREATE DATABASE test_catalog;" -U postgres
  - psql -c "CREATE USER cata WITH PASSWORD 'cata1';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_catalog TO cata;" -U postgres
  - flask db init
  - flask db migrate
  - flask db upgrade
after_success:
  coveralls
script:
- nosetests  --with-coverage --cover-package=myapp
