sudo: true
language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
services:
  - postgresql
env:
  global:
    - export APP_SETTINGS="development"
    - export DATABASE_URL="postgresql://cata:cata1@localhost/test_catalog"
  
before_script:
  - psql -c "CREATE DATABASE test_catalog;" -U postgres
  - psql -c "CREATE USER cata WITH PASSWORD 'cata1';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE test_catalog TO cata;" -U postgres
after_success:
  coveralls
script:
- nosetests  --with-coverage --cover-package=app
